version: "3.9"

services:

  webservice:
    container_name: my_web
    build: .
    depends_on:
      - database
    environment:
      - SECRET_KEY=verysecretKey
      - DEBUG=0
      - DB_NAME=postgres
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=secretpassword
      - ALLOWED_HOSTS=127.0.0.1
    command: make runproxyversion
    networks:
      - nginx_network
      - pg_network
    volumes:
      - static_volume:/app/static

  database:
    container_name: my_database
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=secretpassword
    volumes:
      - database_volume:/var/lib/postgresql/data
    networks:
      - pg_network

  nginx:
    container_name: baysan_nginx
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
    depends_on:
      - webservice
    restart: "on-failure"
    networks:
      - nginx_network
networks:
  nginx_network:
    driver: bridge
  pg_network:
    driver: bridge

volumes:
  database_volume:
  static_volume: